default: list

list:
  @echo "Comandos disponíveis:"
  @echo "   run   - Inicia a aplicação"
  @echo "   build - Constrói a aplicação para produção"
  @echo "   fmt   - Formata todo o código"

run:
  go run ./cmd/educonnect serve

build:
  go build -o bin/app ./cmd/educonnect

fmt:
  go fmt ./...
